name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or master, depending on your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mdserve
        run:
          curl https://github.com/Intellicode/mdserve/releases/download/v0.4.0/mdserve-linux-amd64
          -o /usr/local/bin/mdserve && chmod +x /usr/local/bin/mdserve

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with mdserve
        run: |
          mdserve export ./content  ./out --template ./template.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./out" # This is the default output directory for mdserve

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
